# Generated by Django 5.0.1 on 2024-01-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_anything'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anything',
        ),
    ]
