# Generated by Django 5.0.1 on 2024-01-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_slots_booking_delete_booking_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_booking',
            name='date',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='duration',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='email',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='fromTime',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='licensePlateNo',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='phone_number',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='slot',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='staus',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='toTime',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='slots_booking',
            name='vehicleModel',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
