# Generated by Django 5.0.1 on 2024-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_slots_booking_date_slots_booking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_booking',
            name='otp',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
