# Generated by Django 5.0.1 on 2024-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_slots_booking_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
