# Generated by Django 5.0.1 on 2024-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots_booking',
            name='staus',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
