# Generated by Django 5.0.1 on 2024-02-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_alter_landinformation_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinformation',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
